repos:
  - repo: local
    hooks:
    - id: linter
      name: linter 
      description: Running linter
      entry: rye lint --fix --all --quiet
      types_or: [python, pyi]
      language: python

    - id: format 
      name: format 
      description: Running formatter
      entry: ruff format --all --quiet
      types_or: [python, pyi]
      language: python